name: facial_liveness_verification
description: "Advanced facial liveness detection with anti-spoofing protection for Flutter apps. Includes enterprise-grade security features, customizable UI, and real-time challenge validation."
version: 1.0.0
homepage: https://github.com/InemesitMatthew/Facial-Liveness-Verification
repository: https://github.com/InemesitMatthew/Facial-Liveness-Verification
issue_tracker: https://github.com/InemesitMatthew/Facial-Liveness-Verification/issues
documentation: https://github.com/InemesitMatthew/Facial-Liveness-Verification#readme

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Camera functionality
  camera: ^0.11.2
  
  # Face detection and ML Kit
  google_mlkit_face_detection: ^0.13.1
  
  # Permissions handling
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Additional dev dependencies for package development
  mockito: ^5.4.4
  build_runner: ^2.4.8

# Package configuration
flutter:
  # No assets needed for this package - everything is code-based

# Platform support
platforms:
  android:
  ios:
  windows:
  macos:
  linux:

# Topics for pub.dev discoverability
topics:
  - liveness-detection
  - face-recognition
  - anti-spoofing
  - biometric
  - security
  - ml-kit
  - camera
  - verification
